trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # 1. Zbudowanie obrazu kontenera
  - task: DockerCompose@1
    displayName: 'Budowanie kontenerów'
    inputs:
      action: 'Run a Docker Compose command'
      dockerComposeFile: '**/docker-compose.yml'
      projectName: 'automationtests'
      dockerComposeCommand: 'build'

  # 2. Uruchomienie testów (Zmieniamy na "continueOnError: true", aby krok pozwolił przejść do kopiowania plików)
  - task: DockerCompose@1
    displayName: 'Uruchomienie testów w Docker'
    continueOnError: true # Przejdź dalej, nawet jak testy się wyłożą
    inputs:
      action: 'Run a Docker Compose command'
      dockerComposeFile: '**/docker-compose.yml'
      projectName: 'automationtests'
      dockerComposeCommand: 'up'

  # 3. Kopiujemy pliki z zatrzymanego kontenera
  - script: |
      docker cp $(docker ps -a -q --filter name=automation-tests):/src/TestResults $(System.DefaultWorkingDirectory)/TestResults
    displayName: 'Kopiowanie raportu z wnętrza kontenera'
    condition: succeededOrFailed()

  # 4. PUBLIKOWANIE (Kluczowy krok): Publikuje wyniki i to To ZADANIE OBLUJE POTOK NA CZERWONO
  - task: PublishTestResults@2
    displayName: 'Publikowanie wyników testów w Azure'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '$(System.DefaultWorkingDirectory)/TestResults/*.trx'
      failTaskOnFailedTests: true # Oznaczy to zadanie na CZERWONO, jeśli chociaż 1 test się nie powiódł

  # 5. Wyłączenie środowiska Docker
  - script: |
      docker compose down
    displayName: 'Zamknięcie środowiska Docker'
    condition: succeededOrFailed()
