trigger:
  - main # lub master, zależnie od nazwy Twojej głównej gałęzi

pool:
  vmImage: 'ubuntu-latest' # Uruchamiamy na czystym systemie Linux z zainstalowanym Dockerem

steps:
  - task: DockerCompose@1
    displayName: 'Uruchomienie testów w Docker Compose'
    inputs:
      action: 'Run a Docker Compose command'
      dockerComposeFile: '**/docker-compose.yml'
      projectName: 'automationtests'  # <- TA LINIJKA NAPRAWI BŁĄD
      dockerComposeCommand: 'up --build --exit-code-from automation-tests'
# 2. Opublikowanie raportu w interfejsie Azure DevOps
  - task: PublishTestResults@2
    displayName: 'Publikowanie wyników testów w Azure'
    condition: succeededOrFailed() # Wykonaj ZAWSZE, nawet gdy testy zakończą się niepowodzeniem
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/TestResults/*.trx' # Szuka plików .trx wygenerowanych przez dotnet test